# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 310)
        font = QtGui.QFont()
        font.setFamily("Mona-Sans Regular")
        font.setPointSize(22)
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListView{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_ip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_ip.setGeometry(QtCore.QRect(10, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.le_ip.setFont(font)
        self.le_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.le_ip.setObjectName("le_ip")
        self.btn_send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(330, 260, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_send.setFont(font)
        self.btn_send.setObjectName("btn_send")
        self.pb_progress = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.pb_progress.setGeometry(QtCore.QRect(0, 290, 451, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_progress.setFont(font)
        self.pb_progress.setProperty("value", 24)
        self.pb_progress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pb_progress.setTextVisible(True)
        self.pb_progress.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pb_progress.setInvertedAppearance(False)
        self.pb_progress.setObjectName("pb_progress")
        self.lbl_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(160, 260, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_status.setFont(font)
        self.lbl_status.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lbl_status.setScaledContents(False)
        self.lbl_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lbl_dot = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_dot.setGeometry(QtCore.QRect(100, 260, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_dot.setFont(font)
        self.lbl_dot.setScaledContents(False)
        self.lbl_dot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_dot.setWordWrap(False)
        self.lbl_dot.setObjectName("lbl_dot")
        self.lbl_pic = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_pic.setGeometry(QtCore.QRect(100, 10, 251, 241))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_pic.setFont(font)
        self.lbl_pic.setText("")
        self.lbl_pic.setPixmap(QtGui.QPixmap("assets/files.png"))
        self.lbl_pic.setScaledContents(True)
        self.lbl_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_pic.setObjectName("lbl_pic")
        self.lw_files_to = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lw_files_to.setGeometry(QtCore.QRect(470, 10, 431, 241))
        self.lw_files_to.setObjectName("lw_files_to")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_ip.setText(_translate("MainWindow", "192.168.100.115"))
        self.btn_send.setText(_translate("MainWindow", "send!"))
        self.lbl_status.setText(_translate("MainWindow", "Status:"))
        self.lineEdit.setText(_translate("MainWindow", "8200"))
        self.lbl_dot.setText(_translate("MainWindow", ":"))
