# Form implementation generated from reading ui file 'serverUI.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 350)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(25, 25, 25);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(130, 130, 130);\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: rgb(30, 30, 30);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QListView{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(130, 130, 130);\n"
"\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_savePath = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_savePath.setGeometry(QtCore.QRect(16, 309, 431, 31))
        self.lbl_savePath.setObjectName("lbl_savePath")
        self.btn_close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(454, 310, 101, 31))
        self.btn_close.setObjectName("btn_close")
        self.te_console = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_console.setGeometry(QtCore.QRect(10, 10, 541, 291))
        self.te_console.setObjectName("te_console")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_savePath.setText(_translate("MainWindow", " Files will be saved here:"))
        self.btn_close.setText(_translate("MainWindow", "close"))
